language: minimal
services: docker

branches:
  only:
    - master

before_script:
  - git clone https://github.com/leto1210/docker-dnsmasq.git
  - export TARGET_IMAGE_TAG=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then if [ "$TRAVIS_BRANCH" = "master" ]; then echo "armhf"; else echo "$TRAVIS_BRANCH-armhf"; fi; else echo ""; fi)


script:
  - docker build -t $DOCKER_USERNAME/docker-dnsmasq:$TRAVIS_BUILD_NUMBER .
  - docker tag $DOCKER_USERNAME/docker-dnsmasq:$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/docker-dnsmasq:$TRAVIS_COMMIT
  - docker images
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USERNAME" --password-stdin
  #- docker push $DOCKER_USERNAME/docker-dnsmasq:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USERNAME/docker-dnsmasq:$TRAVIS_COMMIT
  - git clone https://github.com/lukebond/microscanner-wrapper.git
  - MICROSCANNER_TOKEN=$AQUA_TOKEN ./scan.sh $DOCKER_USERNAME/docker-dnsmasq:$TRAVIS_COMMIT

after_success:
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else (echo $TRAVIS_BRANCH) ; fi`
  - docker build -t $DOCKER_USERNAME/docker-dnsmasq:$TAG .
  - docker push $DOCKER_USERNAME/docker-dnsmasq:$TAG

notifications:
  webhooks:
    urls:
      - https://hooks.microbadger.com/images/leto1210/docker-dnsmasq/yHnTY1fBVjlf1UKlN6swxAEIrts=
    on_success: always # default: always
    #on_failure: always # default: always
    #on_start:   change # default: never
    #on_cancel:  always # default: always
    #on_error:   always # default: always
